import React from 'react';
import {
    Row,
    Col
} from 'react-bootstrap';
import './index.scss';
import parse from 'html-react-parser';
import axios from 'axios';
import ConfigureAxios from '@/utils/axiosConfig';

async function getTermsConditionInfo(){
    ConfigureAxios();
    const response=axios.get(`/public/static-pages/terms-&-conditions`).then((res)=>{
        if(res.status===200){
            //console.log("Products : ",res.data);
            return res.data;
        }
    }).catch((error)=>{
      //console.log(error)
      console.log("Get Terms & Condition Error.")
      return [];
    });
  
    return response;
}

export const metadata = {
    title: 'The Korean Shoap BD - Terms & Condition',
    // description: 'Generated by create next app',
}
export default async function TermsAndConditionPage(){
    const data=await getTermsConditionInfo();
    //console.log("Data : ",data)
    return(
        <>
            <Row
            className='privacy-policy-container'
            >
                {data?.content?parse(data.content):""}
            </Row>
        </>
    )
}