import React from 'react';
import {
    Row,
    Col
} from 'react-bootstrap';
import TopBanner from '../../TopBanner';
import ProductsMain from './partials/ProductsMain';
import SlugInfo from './partials/SlugsInfo';
import ConfigureAxios from '@/utils/axiosConfig';
import axios from 'axios';
import parse from 'html-react-parser';

async function getCategoryInfos({slugs}){
    //console.log("params: ",slugs);
    ConfigureAxios();
    const response=axios.get(`/public/seo-contents/category/${slugs}`).then((res)=>{
        if(res.status===200){
            //console.log("Products : ",res.data);
            return res.data;
        }
    }).catch((error)=>{
      //console.log(error)
      //console.log("Get Category Slugs Error.")
      return [];
    });
  
    return response;
}
export const metadata = {
    title: 'The Korean Shop BD - Category',
    // description: 'Generated by create next app',
}

async function ProductsBrandsSlugPage({params}){
    //const data=await getCategoryInfos(params);

    return(
        <>
            <Row>
                <Col 
                xs={12}
                
                >
                    <TopBanner/>
                </Col>
            </Row>
            <Row>
                <Col xs={12}>
                    <ProductsMain
                    params={params}
                    />
                </Col>
            </Row>
            <SlugInfo params={params}/>
        </>
    )
}
export default ProductsBrandsSlugPage;