// import { Inter } from 'next/font/google'
import './globals.css';
import 'bootstrap/dist/css/bootstrap.css';
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import {
  Row,
  Col
} from 'react-bootstrap'
import Container from 'react-bootstrap/Container'
import HeaderMain from './shared/Header';
import FooterMain from './shared/Footer';
import MobileFooterMenu from './shared/Header/Mobile/MobileFooterMenu';
import BodyContainer from './BodyContainer';
import FlatButton from './FlatButton';

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Korean Mall BD - Korean Cosmetics and Skin Care Products.',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png" sizes="any" />
        <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js" async ></script>
      </head>
      <body >
        {/* <FlatButton/> */}
        <Container fluid>
          <HeaderMain/>
          {/* <Container> */}
            
          <BodyContainer>
            {children}
          </BodyContainer>
        
          {/* </Container> */}
          <FooterMain/>
          <MobileFooterMenu/>
        </Container>
      </body>
    </html>
  )
}
