import React from 'react';
import {
    Row,
    Col
} from 'react-bootstrap';
import './index.scss';
import parse from 'html-react-parser';
import axios from 'axios';
import ConfigureAxios from '@/utils/axiosConfig';

async function getPrivacyPolicyDetails(){
    ConfigureAxios();
    const response=axios.get('/public/static-pages/privacy-policy').then((res)=>{
        if(res.status===200){
            //console.log("Products : ",res.data);
            return res.data;
        }
    }).catch((error)=>{
      //console.log(error)
      console.log("Get Body Serum Lists Error.")
      return [];
    });
  
    return response;
}

export const metadata = {
    title: 'The Korean Shoap BD - Privacy and Policy',
    // description: 'Generated by create next app',
}
export default async function PrivacyPolicyPage(){
    const data=await getPrivacyPolicyDetails();
    //console.log("Data : ",data)
    return(
        <>
            <Row
            className='privacy-policy-container'
            >
                {data?.content?parse(data.content):""}
            </Row>
        </>
    )
}