import React from 'react';
import {
    Row,
    Col
} from 'react-bootstrap';
import TopBanner from '../../TopBanner';
import ProductsMain from './partials/ProductsMain';
import ConfigureAxios from '@/utils/axiosConfig';
import axios from 'axios';
import parse from 'html-react-parser';

async function getBrandsInfos({slugs}){
    //console.log("params: ",slugs);
    ConfigureAxios();
    const response=axios.get(`/public/seo-contents/brand/${slugs}`).then((res)=>{
        if(res.status===200){
            //console.log("Products : ",res.data);
            return res.data;
        }
    }).catch((error)=>{
      //console.log(error)
      //console.log("Get Brands Slugs Error.")
      return [];
    });
  
    return response;
}
export const metadata = {
    title: 'The Korean Shoap BD - Brand',
    // description: 'Generated by create next app',
}

async function ProductsBrandsSlugPage({params}){
    const data=await getBrandsInfos(params);
    //console.log(data)
    return(
        <>
            <Row>
                <Col 
                xs={12}
                
                >
                    <TopBanner/>
                </Col>
            </Row>
            <Row>
                <Col xs={12}>
                    <ProductsMain
                    params={params}
                    />
                </Col>
            </Row>
            {
                data?.content?(
                    <Row>
                        <Col
                        className='home-page-footer-seo-content'
                        >
                            {data?.content?parse(data.content):""}
                        </Col>
                    </Row>
                ):""
            } 
        </>
    )
}
export default ProductsBrandsSlugPage;